version: '3.2'

services:
    
  redis:
    env_file:
      - ./config/.env
    image: redis
    ports:
      - 6380:6379
    networks:
      - backend
    restart: always
    command: "redis-server --requirepass ${REDIS_PASSWORD}"

  minio:
    env_file:
      - config/.env
    image: minio/minio
    volumes:
      - ./dfs/data:/data
      - ./config/.minio:/root/.minio
    ports:
      - 9001:9000
    command: server /data
    networks:
      - backend
    restart: always

  db:
    env_file:
      - ./config/.env
    image: mariadb
    ports:
      - 3307:3306
    command:
      - --interactive_timeout=28800
    networks:
      - frontend
    restart: always

  proxy:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - frontend
    restart: always
    depends_on:
       - lam
    #  - api
    #  - web

  ldap:
    env_file:
        - ./config/.env
    image: osixia/openldap:1.3.0
    ports:
        - 389:636
    networks:
        - backend
    restart: always

  lam:
    env_file:
        - ./config/.env
    image: ldapaccountmanager/lam:7.0
    ports: 
        - 80:80
    networks:
        - backend
    restart: always


networks:
  frontend:
  backend: