version: '3.2'

services:
  api:
    env_file:
      - ./config/.env
    build:
        context: server/
        dockerfile: api/Dockerfile
    ports: 
        - 2020:2020
    networks:
        - backend
        - frontend
    command: "/bin/sh /tools/wait-for.sh db:3306 -- \
              /bin/sh /tools/wait-for.sh minio:9000 -- \
              /bin/sh /tools/wait-for.sh redis:6379 -- \
              python3 /api/app.py"

  web:
    build: ./server/web
    networks:
      - frontend
    restart: always
    depends_on:
      - api

  redis:
    env_file:
      - ./config/.env
    image: redis
    ports:
      - 6380:6379
    networks:
      - backend
    restart: always
    command: "redis-server --requirepass ${REDIS_PASSWORD}"

  minio:
    env_file:
      - config/.env
    image: minio/minio
    volumes:
      - ./dfs/data:/data
      - ./config/.minio:/root/.minio
    ports:
      - 9001:9000
    command: server /data
    networks:
      - backend
    restart: always

  db:
    env_file:
      - ./config/.env
    image: mariadb
    ports:
      - 3307:3306
    command:
      - --interactive_timeout=28800
    networks:
      - backend
    restart: always

  proxy:
    image: nginx:alpine
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - frontend
    restart: always
    depends_on:
       - lam
       - api
    #  - web

  ldap:
    env_file:
        - ./config/.env
    image: osixia/openldap:1.3.0
    ports:
      - 389:389
    networks:
        backend:
          aliases:
            - ldap
            - ldap.openweblib.com
    restart: always

  lam:
    env_file:
        - ./config/.env
    image: ldapaccountmanager/lam:7.0
    ports: 
        - 3030:80
    networks:
        - frontend
        - backend
    restart: always
  
  auth-proxy:
    env_file:
      - ./config/.env
    build:
      context: server/nginx-ldap-auth
      dockerfile: Dockerfile
    networks:
        - frontend
        - backend
    

networks:
  frontend:
  backend: